x1=int(input("enter value of x1:"))
x2=int(input("enter value of x2:"))
y1=int(input("enter value of y1:"))
y2=int(input("enter value of y2:"))
slop=float((y2-y1)/(x2-x1))
print("slope is :",slop)